#!/usr/bin/env python3
"""Convert Terminus ter-u16n.bdf (8x16) into a 10x16 cell C header.

Official Terminus sizes jump 8x16 -> 10x18; there is no stock 10x16.
We keep authentic Terminus 8x16 glyphs and center them in a 10-wide cell
(1 px pad left/right) so 80 columns fill an 800 px CrowPanel width.
25 rows x 16 = 400 px console + 80 px chrome on 480.

Bit order matches font4x8.h: bit 0 = leftmost pixel.
License: SIL OFL 1.1 (Terminus / Dimitar Toshkov Zhekov).
"""
from __future__ import annotations

import pathlib
import re
import sys

CELL_W = 10
CELL_H = 16
SRC_W = 8


def parse_bdf(path: pathlib.Path) -> dict[int, list[int]]:
    text = path.read_text(encoding="utf-8", errors="replace")
    glyphs: dict[int, list[int]] = {}
    enc = None
    in_bitmap = False
    rows: list[int] = []
    for line in text.splitlines():
        if line.startswith("ENCODING "):
            enc = int(line.split()[1])
            rows = []
            in_bitmap = False
        elif line.strip() == "BITMAP":
            in_bitmap = True
            rows = []
        elif line.strip() == "ENDCHAR":
            if enc is not None and rows:
                # Normalize to CELL_H rows of SRC_W bits (MSB-left from BDF).
                while len(rows) < CELL_H:
                    rows.append(0)
                glyphs[enc] = rows[:CELL_H]
            enc = None
            in_bitmap = False
            rows = []
        elif in_bitmap:
            # One hex word per row; width may be 8 or 16 bits in file.
            hx = line.strip()
            if not hx:
                continue
            val = int(hx, 16)
            # If more than 8 bits were stored, take the top SRC_W bits.
            bitlen = max(8, len(hx) * 4)
            val >>= max(0, bitlen - SRC_W)
            rows.append(val & 0xFF)
    return glyphs


def bdf_row_to_cell(bdf_row: int) -> int:
    """BDF MSB-left 8-bit row -> our bit0-left 10-bit cell (centered)."""
    out = 0
    for x in range(SRC_W):
        if bdf_row & (0x80 >> x):
            out |= 1 << x
    return (out << 1) & ((1 << CELL_W) - 1)  # +1 px left pad


def main() -> int:
    root = pathlib.Path(__file__).resolve().parents[1]
    bdf = pathlib.Path(__file__).resolve().parent / "terminus_build" / "ter-u16n.bdf"
    if len(sys.argv) > 1:
        bdf = pathlib.Path(sys.argv[1])
    out = root / "font10x16.h"
    if len(sys.argv) > 2:
        out = pathlib.Path(sys.argv[2])

    glyphs = parse_bdf(bdf)
    print(f"parsed {len(glyphs)} glyphs from {bdf.name}")

    lines: list[str] = []
    lines.append("// 10x16 monospace console font for CrowPanel (80 cols x 25 rows).")
    lines.append("// Glyphs: Terminus Medium 8x16 (ter-u16n), centered in a 10x16 cell.")
    lines.append("// Source: Terminus Font (SIL OFL 1.1) — Dimitar Toshkov Zhekov")
    lines.append("// https://terminus-font.sourceforge.net/")
    lines.append("//")
    lines.append("// Geometry: 80*10=800, 25*16=400 (80 px left for status on 480-tall panel).")
    lines.append("// Each uint16_t = one row; bit 0 = leftmost pixel (same convention as font4x8.h).")
    lines.append("// Generated by tools/gen_font10x16_terminus.py — do not hand-edit.")
    lines.append("#pragma once")
    lines.append("#include <stdint.h>")
    lines.append("#include <pgmspace.h>")
    lines.append("")
    lines.append("#define FONT10X16_W 10")
    lines.append("#define FONT10X16_H 16")
    lines.append("#define FONT10X16_COLS 80")
    lines.append("#define FONT10X16_ROWS 25")
    lines.append("")
    lines.append("static const uint16_t font10x16[256][16] PROGMEM = {")

    present = 0
    # Hand-crafted VT100 special-graphics box drawing (ESC ( 0). Matches the
    # GLYPH_* slots in console.cpp (0x80..0x8A). Stem on bits 4+5; H on rows 7-8.
    V = 0x030
    H = 0x3FF
    HR = 0x3F0  # center through right
    HL = 0x03F  # left through center
    vt100 = {
        0x80: [0]*7 + [H, H] + [0]*7,                          # HLINE
        0x81: [V] * 16,                                         # VLINE
        0x82: [0]*7 + [HR, HR] + [V]*7,                         # UL
        0x83: [0]*7 + [HL, HL] + [V]*7,                         # UR
        0x84: [V]*7 + [HR, HR] + [0]*7,                         # LL
        0x85: [V]*7 + [HL, HL] + [0]*7,                         # LR
        0x86: [V]*7 + [HR, HR] + [V]*7,                         # LTEE
        0x87: [V]*7 + [HL, HL] + [V]*7,                         # RTEE
        0x88: [V]*7 + [H, H] + [0]*7,                           # BTEE
        0x89: [0]*7 + [H, H] + [V]*7,                           # TTEE
        0x8A: [V]*7 + [H, H] + [V]*7,                           # CROSS
    }

    for cp in range(256):
        if cp in vt100:
            cell = vt100[cp]
            present += 1
        else:
            src = glyphs.get(cp)
            if src is None:
                cell = [0] * CELL_H
            else:
                cell = [bdf_row_to_cell(r) for r in src]
                present += 1
        body = ",".join(f"0x{v:03X}" for v in cell)
        lines.append(f"  {{{body}}},  // 0x{cp:02X}")

    lines.append("};")
    lines.append("")
    out.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {out} ({present}/256 codepoints from BDF)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
